### ISSUE TITLE
Updating Repos doesn't work?

### ISSUE THREAD

**Issue by tammo0** [OpenParliamentTV/OpenParliamentTV-Conductor#3]
Running ./optv outputs following warning at the end:

`Updating OpenParliamentTV-Tools
./optv: line 75: cd: OpenParliamentTV-Tools: No such file or directory
Updating OpenParliamentTV-Data-DE
./optv: line 75: cd: OpenParliamentTV-Data-DE: No such file or directory
`

**Comment by oaubert** [comment]
Looks like optv is not run from a directory which has been propertly initialize (`optv init`), it does not find either the tools or data directories.

**Comment by oaubert** [comment]
Note that the location of the script itself is important, it is used to determine the basedir of everything.

**Comment by tammo0** [comment]
Its running from the cronjob with an absolute path to it:
`/var/www/html/OpenParliamentTV-Conductor/optv pull update pull publish >/dev/null 2>&1`
so this should be fine you say?
`cd /var/www/html/OpenParliamentTV-Conductor/ && ./optv pull update pull publish >/dev/null 2>&1`

**Comment by tammo0** [comment]
Running it inside the directory `/var/www/html/OpenParliamentTV-Conductor/` with `./optv pull update pull publish` the info about the missing repos appear, even if `./optv check` outputs `All checks OK`

**Comment by tammo0** [comment]
Maybe its because we change directories [here](https://github.com/OpenParliamentTV/OpenParliamentTV-Conductor/blob/main/optv#L143) and don't return back to the basedir, so the second `pull` in the command chain is executed not in the basedir?

**Comment by oaubert** [comment]
You do not have to    cd  yourself, the script does it upon starting. Do the /var/www/html/OpenParliamentTV-Conductor/OpenParliamentTV-Data-DE/ and /var/www/html/OpenParliamentTV-Conductor/OpenParliamentTV-Tools  directories exist?

**Comment by tammo0** [comment]
All right.
Yes, both exist and are found at the first part of the command chain.

here is the complete output running optv in the directory /var/www/html/OpenParliamentTV-Conductor:


> /var/www/html/OpenParliamentTV-Conductor# ./optv pull update pull publish
> Updating main
> hint: Pulling without specifying how to reconcile divergent branches is
> hint: discouraged. You can squelch this message by running one of the following
> hint: commands sometime before your next pull:
> hint:
> hint:   git config pull.rebase false  # merge (the default strategy)
> hint:   git config pull.rebase true   # rebase
> hint:   git config pull.ff only       # fast-forward only
> hint:
> hint: You can replace "git config" with "git config --global" to set a default
> hint: preference for all repositories. You can also pass --rebase, --no-rebase,
> hint: or --ff-only on the command line to override the configured default per
> hint: invocation.
> Already up to date.
> Updating OpenParliamentTV-Tools
> hint: Pulling without specifying how to reconcile divergent branches is
> hint: discouraged. You can squelch this message by running one of the following
> hint: commands sometime before your next pull:
> hint:
> hint:   git config pull.rebase false  # merge (the default strategy)
> hint:   git config pull.rebase true   # rebase
> hint:   git config pull.ff only       # fast-forward only
> hint:
> hint: You can replace "git config" with "git config --global" to set a default
> hint: preference for all repositories. You can also pass --rebase, --no-rebase,
> hint: or --ff-only on the command line to override the configured default per
> hint: invocation.
> Already up to date.
> Updating OpenParliamentTV-Data-DE
> hint: Pulling without specifying how to reconcile divergent branches is
> hint: discouraged. You can squelch this message by running one of the following
> hint: commands sometime before your next pull:
> hint:
> hint:   git config pull.rebase false  # merge (the default strategy)
> hint:   git config pull.rebase true   # rebase
> hint:   git config pull.ff only       # fast-forward only
> hint:
> hint: You can replace "git config" with "git config --global" to set a default
> hint: preference for all repositories. You can also pass --rebase, --no-rebase,
> hint: or --ff-only on the command line to override the configured default per
> hint: invocation.
> Already up to date.
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  422k    0  422k    0     0  1683k      0 --:--:-- --:--:-- --:--:-- 1683k
> Updating data for DE into /var/www/html/OpenParliamentTV-Conductor/OpenParliamentTV-Data-DE
> Updating main
> hint: Pulling without specifying how to reconcile divergent branches is
> hint: discouraged. You can squelch this message by running one of the following
> hint: commands sometime before your next pull:
> hint:
> hint:   git config pull.rebase false  # merge (the default strategy)
> hint:   git config pull.rebase true   # rebase
> hint:   git config pull.ff only       # fast-forward only
> hint:
> hint: You can replace "git config" with "git config --global" to set a default
> hint: preference for all repositories. You can also pass --rebase, --no-rebase,
> hint: or --ff-only on the command line to override the configured default per
> hint: invocation.
> Already up to date.
> Updating OpenParliamentTV-Tools
> **./optv: line 75: cd: OpenParliamentTV-Tools: No such file or directory**
> Updating OpenParliamentTV-Data-DE
> **./optv: line 75: cd: OpenParliamentTV-Data-DE: No such file or directory**
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  422k    0  422k    0     0  1408k      0 --:--:-- --:--:-- --:--:-- 1408k
> On branch main
> Your branch is up to date with 'origin/main'.
> 
> nothing to commit, working tree clean
> Everything up-to-date
